# Generated by Django 5.2.17 on 2026-10-05 21:08

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0003_eventoprocessado_pedido_pedidoitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='correlation_id',
            field=models.CharField(blank=True, default='', max_length=36),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('PROCESSANDO', 'Processando'), ('PAGO', 'Pago'), ('CANCELADO', 'Cancelado'), ('FALHA', 'Falha')], default='PENDENTE', max_length=20),
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('APROVADO', 'Aprovado'), ('RECUSADO', 'Recusado')], default='APROVADO', max_length=10)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('forma_pagamento', models.CharField(choices=[('cartao_credito', 'Cartão de crédito'), ('cartao_debito', 'Cartão de débito'), ('pix', 'Pix'), ('boleto', 'Boleto')], default='cartao_credito', max_length=20)),
                ('referencia', models.CharField(max_length=40, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processado_em', models.DateTimeField(blank=True, null=True)),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pagamento', to='repositories.pedido')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinatario', models.CharField(max_length=180)),
                ('canal', models.CharField(choices=[('EMAIL', 'E-mail'), ('SMS', 'SMS'), ('WHATSAPP', 'WhatsApp')], default='EMAIL', max_length=10)),
                ('assunto', models.CharField(max_length=160)),
                ('conteudo', models.TextField()),
                ('evento_origem', models.CharField(max_length=36, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notificacoes', to='repositories.pedido')),
                ('pagamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notificacoes', to='repositories.pagamento')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='pagamento',
            index=models.Index(fields=['status'], name='idx_pagamento_status'),
        ),
        migrations.AddIndex(
            model_name='notificacao',
            index=models.Index(fields=['canal', '-created_at'], name='idx_notificacao_canal'),
        ),
    ]
